eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/
server:
  port: 8093
spring:
  application:
    name: service-zuul
zuul:
  routes:
    ribbon:
      path: /api-ribbon/**
      serviceId: service-ribbon
    feign:
      path: /api-feign/**
      serviceId: service-feign
  ignored-services: '*'