eureka:
  client:
    service-url:
      defaultZone: http://eureka-server-1:8080/eureka/, http：//eureka-server-2:8083/eureka # 注册Eureka server
server:
  port: 8093
spring:
  application:
    name: service-zuul
zuul:
  routes:
    ribbon:
      path: /api-ribbon/**
      serviceId: service-ribbon
    feign:
      path: /api-feign/**
      serviceId: service-feign
  ignored-services: '*'