spring:
  application:
    name: server-turbine
server:
  port: 8051
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server-1:8061/eureka, http://eureka-server-2:8062/eureka # 注册Eureka server
turbine:
  combine-host-port: true
  app-config: server-ribbon,server-figen
#  cluster-name-expression: metadata['cluster']
#  aggregator:
#    cluster-config: ribbon
  instanceUrlSuffix: /hystrix.stream