spring:
  application:
    name: server-turbine
server:
  port: 8051
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server-1:8061/eureka, http://eureka-server-2:8062/eureka # 注册Eureka server
turbine:
  combine-host-port: true
  app-config: server-ribbon,server-feign # 配置eureka server中的serverid列表，用来表示监控哪些服务
  cluster-name-expression: new String("default")
  aggregator:
    cluster-config: default # 指定聚合哪些集群，多个使用“，”分割，默认为default
  instanceUrlSuffix: /hystrix.stream