eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server-1:18061/eureka, http://eureka-server-2:18062/eureka # 注册Eureka server
server:
  port: 18072 # 服务端口号
spring:
  application:
    name: service-demo # 服务名

management: # actuator
  server:
    port: 18072
  endpoints:
    web:
      base-path: /    # 默认路径为 /actuator
      exposure:
        include: refresh,health,info
#       include: "*"    # 打开全部服务权限