eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka/ #\u914D\u7F6Eeureka\u670D\u52A1\u5668\u5730\u5740
server:
  port: 8091
spring:
  application:
    name: service-ribbon
