eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server-1:8061/eureka, http://eureka-server-2:8062/eureka # 注册Eureka server

server:
  port: 8092

spring:
  application:
    name: server-feign

feign:
  hystrix:
    enabled: true

management:
      security: false
      endpoints:
        web:
          exposure:
            include: hystrix.stream
          base-path: /