server:
  port: 8083  # \u5F53\u524Deureka server \u670D\u52A1\u7684\u7AEF\u53E3\u53F7\u4E3A8080
eureka:
  instance:
    hostname: eureka-server-2 # \u5F53\u524Deureka \u7684hostname \u4E3A eureka-server-2
  client:
    register-with-eureka: false # \u5F53\u524D\u670D\u52A1\u4E0D\u9700\u8981\u5230eureka server\u4E0A\u6CE8\u518C\u4E3A\u5BA2\u6237\u7AEF
    fetch-registry: false #\u4E0D\u8FDB\u884C\u670D\u52A1\u68C0\u7D22
    serviceUrl: # eureka\u670D\u52A1\u5730\u5740
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
       defaultZone: http://eureka-server-1:8080/eureka
  server:
    enable-self-preservation: false # \u8BBE\u4E3Afalse\uFF0C\u5173\u95ED\u81EA\u6211\u4FDD\u62A4
    eviction-interval-timer-in-ms: 4000 # \u6E05\u7406\u95F4\u9694\uFF08\u5355\u4F4D\u6BEB\u79D2\uFF0C\u9ED8\u8BA4\u662F60*1000\uFF09