eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/ #\u914D\u7F6Eeureka\u670D\u52A1\u5668\u5730\u5740
server:
  port: 8082 #\u914D\u7F6Eeurekaclient\u7684\u670D\u52A1\u7AEF\u53E3
spring:
  application:
    name: service-client #\u914D\u7F6Eeurekaclient\u7684\u670D\u52A1\u540D\u79F0