eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/ # 注册Eureka
server:
  port: 8081 # 服务端口号
spring:
  application:
    name: service-client_1 # 应用名称

management: # actuator
  server:
    port: 8081
  endpoints:
    web:
      base-path: /    # 默认路径为 /actuator
      exposure:
        include: refresh,health,info
#       include: "*"    # 打开全部服务权限