eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server-1:8080/eureka/, http：//eureka-server-2:8083/eureka # 注册Eureka server

server:
  port: 8092

spring:
  application:
    name: service-feign

feign:
  hystrix:
    enabled: true

management:
      security: false
      endpoints:
        web:
          exposure:
            include: hystrix.stream
          base-path: /