eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/

server:
  port: 8092

spring:
  application:
    name: service-feign

feign:
  hystrix:
    enabled: true

management:
      security: false
      endpoints:
        web:
          exposure:
            include: hystrix.stream
          base-path: /