server:
  port: 8062  # 当前eureka server 服务的端口号为8080
eureka:
  instance:
    hostname: eureka-server-2 # 当前eureka 的hostname 为 eureka-server-2
  client:
    register-with-eureka: false #当前服务不需要到eureka server上注册为客户端
    fetch-registry: false #不进行服务检索
    serviceUrl: # eureka服务地址
#      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
       defaultZone: http://eureka-server-1:8061/eureka
  server:
    enable-self-preservation: false # 设为false，关闭自我保护，防止由于eureka的机制导致 client 被错误显示在线，在开发环境使用
    eviction-interval-timer-in-ms: 4000 # 清理间隔（单位毫秒，默认是60*1000）