eureka:
  client:
    service-url:
      defaultZone: http://eureka-server-1:18061/eureka, http://eureka-server-2:18062/eureka # 注册Eureka server
server:
  port: 8080
spring:
  application:
    name: server-zuul
zuul:
  routes:
    ribbon:
      path: /api-ribbon/**
      serviceId: server-ribbon
    feign:
      path: /api-feign/**
      serviceId: server-feign
  ignored-services: '*'