eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server-1:8080/eureka/, http://eureka-server-2:8083/eureka/  #Eureka Server服务注册
server:
  port: 8090

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/lautrix/Spring-Cloud-Netflix_TechPra.git # 配置文件远程服务器地址
          searchPaths: ConfigFiles  # 配置文件相对路径
          label: master
#          username: repo_username   # 当远程服务器为私有库时才需要填写
#          password: repo_password
          force-pull: true
  application:
    name: config-server
