eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server-1:18061/eureka, http://eureka-server-2:18062/eureka # 注册Eureka server
server:
  port: 18041 #当前服务注册端口号

spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/lautrix/Spring-Cloud-Netflix_TechPra.git # 配置文件远程服务器地址
          searchPaths: ConfigFiles  # 配置文件相对路径
          label: master # 分支
#          username: repo_username   # 当远程服务器为私有库时才需要填写
#          password: repo_password
          force-pull: true
  application:
    name: config-server